\documentclass{article}

\begin{document}

<<>>=
library(celda)
library(tidyverse)
@

<<>>=
# Step 1: load data in both the mouse and human cells (TOD)
# 10,280 cells and 24,976 mouse genes
setwd("~/Documents/projects/spatial-genomics/data")

tod_x <- read.csv("./all_batches_concat_mouse_genes_only/X.csv", stringsAsFactors = F,
                    header = F, row.names = NULL)
tod_obs <- read.csv("./all_batches_concat_mouse_genes_only/obs.csv", stringsAsFactors = F)
tod_var <- read.csv("./all_batches_concat_mouse_genes_only/var.csv", stringsAsFactors = F)

colnames(tod_obs)[1] <- "cell_iden"
colnames(tod_var)[1] <- "gene_iden"

tod_obs$cell_iden <- make.names(tod_obs$cell_iden, allow_ = F)
rownames(tod_x) <- tod_obs$cell_iden
colnames(tod_x) <- tod_var$gene_iden

# Step 2: select mouse cells only (TOC)
mouse_cell_idx <- which(tod_obs$CellType != "Hek293t")
human_cell_idx <- which(tod_obs$CellType == "Hek293t")
toc_obs <- tod_obs[mouse_cell_idx, ]
toc_var <- tod_var
toc_x <- tod_x[mouse_cell_idx, ]

# Step 3: load in plot coordinates
plot_coords <- read.csv("./all_batches_mouse_only_dim_plot_coordinates.csv", 
                        stringsAsFactors = F)
colnames(plot_coords)[1] <- "cell_iden"
plot_coords$cell_iden <- make.names(plot_coords$cell_iden, allow_ = F)

# merge coords info into toc_obs
toc_obs_coords <- toc_obs %>%
  left_join(plot_coords[, c("cell_iden", "X_umap1", "X_umap2", "X_tsne1", "X_tsne2")],
            by = "cell_iden")
@

<<decontX-toc>>=
toc_decont <- decontX(x = as.matrix(t(toc_x)), z = toc_obs$CellType)
length(toc_decont$contamination)
summary(toc_decont$contamination[which(toc_obs$CellType == "mc38")])
summary(toc_decont$contamination[which(toc_obs$CellType == "Hepatocyte")])
summary(toc_decont$contamination)

toc_decont_df <- data.frame(cell_iden = toc_obs$cell_iden,
                            CellType = toc_obs$CellType, 
                            count = toc_decont$contamination)
write.csv(toc_decont_df, file = "~/Documents/Github/spatial-genomics/data/mouse_only-before.csv")

ggplot(toc_decont_df, aes(x = CellType, y = count)) +
  geom_violin(colour = "red") + 
  geom_jitter(shape = 16, position=position_jitter(0.2), size = 0.3, alpha = 0.3) +
  theme_bw() +
  ylab("Estimated contamination fraction in each cell") +
  xlab("Cell type")

ggsave("~/Documents/Github/spatial-genomics/fig/contamination/mouse_only-before.png")

toc_decont_df %>% group_by(CellType) %>%
  summarise(median = median(count, na.rm = T))
@

<<>>=
hek293t_contam_result <- read.csv("~/Documents/projects/spatial-genomics/data/hek293t_contam_result.csv", row.names = 1)
contam_genes <- hek293t_contam_result[hek293t_contam_result$contam == T, "gene_name"]

dim(toc_x) # 7335 cells by 24976 genes
toc_x_update <- toc_x[, ! colnames(toc_x) %in% contam_genes]
nonzero_cells <- which(rowSums(toc_x_update) != 0) # 4 cells with zero counts
# sum(rownames(toc_x) == toc_obs$cell_iden)
toc_x_new <- toc_x_update[nonzero_cells, ] # 7335 cells by 24917 genes
toc_obs_new <- toc_obs[nonzero_cells, ]

toc_decont_new <- decontX(x = as.matrix(t(toc_x_new)), z = toc_obs_new$CellType)

toc_decont_new_df <- data.frame(cell_iden = toc_obs_new$cell_iden,
                                CellType = toc_obs_new$CellType, 
                                count = toc_decont_new$contamination)
write.csv(toc_decont_new_df, file = "~/Documents/Github/spatial-genomics/data/mouse_only-after.csv")

ggplot(toc_decont_new_df, aes(x = CellType, y = count)) +
  geom_violin(colour = "blue") + 
  geom_jitter(shape = 16, position=position_jitter(0.2), size = 0.3, alpha = 0.3) +
  theme_bw() +
  ylab("Estimated contamination fraction in each cell") +
  xlab("Cell type")
ggsave("~/Documents/Github/spatial-genomics/fig/contamination/mouse_only-after.png")

toc_decont_new_df %>% group_by(CellType) %>%
  summarise(median = median(count, na.rm = T))

toc_decont_merge <- left_join(toc_decont_df, 
                              toc_decont_new_df[, c("cell_iden", "count")], 
                              by = "cell_iden")



toc_decont_merge_long <- reshape(toc_decont_merge, 
                                 direction = "long",
                                 varying = c("count.x", "count.y"), 
                                 idvar = "cell_iden")


ggplot(toc_decont_merge_long, aes(x = count)) +
    geom_density(aes(color = time), alpha = 0.7) +
    facet_wrap(~ CellType) +
    scale_color_manual(name = "Remove contaminated genes", 
                         breaks = c("x", "y"),
                         label = c("before", "after"),
                         values = c("red", "blue")) +
    xlab("estimated contamination rate per cell") +
    theme_bw() +
    theme(legend.position = "bottom")
  
ggsave("~/Documents/Github/spatial-genomics/fig/contamination/mouse_only-compare.png")
@


\end{document}