\documentclass{article}

\begin{document}

<<package>>=
library(NMF)
library(toOrdinal)
@

<<data>>=
spleen_myeloid_mat_nn <- readRDS("~/Documents/projects/spatial-genomics/nmf_result/spleen_myeloid_mat_nn.rds")
nmf_res_spleen_myeloid <- readRDS("~/Documents/projects/spatial-genomics/nmf_result/seurat_nmf_res_spleen_myeloid.rds")
nmf_res_spleen_myeloid@fit

liver_myeloid_mat_nn <- readRDS("~/Documents/projects/spatial-genomics/nmf_result/liver_myeloid_mat_nn.rds")
nmf_res_liver_myeloid <- readRDS("~/Documents/projects/spatial-genomics/nmf_result/seurat_nmf_res_liver_myeloid.rds")
nmf_res_liver_myeloid@fit
@

<<liver-module>>=
s_liver <- extractFeatures(nmf_res_liver_myeloid, 200L)

num_liver_modules <- 20
liver_module <- data.frame(rep(NA, 100))

for(i in 1:num_liver_modules){
  liver_module <- cbind(liver_module, 
                        substring(rownames(liver_myeloid_mat_nn)[s_liver[[i]]], 6))
}

liver_module <- liver_module[, -1]
colnames(liver_module) <- paste0("module", 1:num_liver_modules)
dim(liver_module)
@

<<spleen-module>>=
s_spleen <- extractFeatures(nmf_res_spleen_myeloid, 200L)

num_spleen_modules <- 20
spleen_module <- data.frame(rep(NA, 100))

for(i in 1:num_spleen_modules){
  spleen_module <- cbind(spleen_module, 
                         substring(rownames(spleen_myeloid_mat_nn)[s_spleen[[i]]], 8))
}

spleen_module <- spleen_module[, -1]
colnames(spleen_module) <- paste0("module", 1:num_spleen_modules)
dim(spleen_module)
@

<<overlap>>=
overlap_mat <- matrix(NA, nrow = num_liver_modules, ncol = num_spleen_modules)
for(i in 1:num_liver_modules){
  for(j in 1:num_spleen_modules){
    overlap_mat[i, j] <- sum(liver_module[, i] %in% spleen_module[, j])
  }
}

for(i in 1:num_liver_modules){
  cat(paste0("\n", i, " - In the top 200 genes of ", toOrdinal(i), " LIVER module, ",
               max(overlap_mat[i, ]), " genes are identified in the ", 
               toOrdinal(which.max(overlap_mat[i, ])), " SPLEEN module: \n"
               ), 
      file = "~/Documents/projects/spatial-genomics/nmf_result/overlap_myeloid_gene_list.txt", 
      append = T)
 
 cat(liver_module[, i][which(liver_module[, i] %in% spleen_module[, which.max(overlap_mat[i, ])])], 
     "\n", 
      file = "~/Documents/projects/spatial-genomics/nmf_result/overlap_myeloid_gene_list.txt", 
      append = T)
}
@

\end{document}